[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "8.19.3"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[plugins]]
  package = "@netlify/plugin-gatsby"